### ISSUE TITLE
destructor not called

### ISSUE THREAD

**Issue by timotheecour** [kaushalmodi/std_vector#4]
```nim
when true: # D20200511T194815:here gitissue
  import pkg/std_vector
  type Foo = object
    x: int
  proc `=destroy`*(a: var Foo) {.inline.} =
    echo ("in destroy", a.x)
  proc main =
    var v1 = newVector[Foo]()
    echo v1
    var v = newVector[Foo]()
    v.add Foo(x: 10)
    v.add Foo(x: 11)
    v.add Foo(x: 12)
    echo "ok0"
    echo v
    echo "ok1"
    v[0] = Foo(x:111)
    echo "ok1"
    echo v
    echo "done"
  main()
```

```
v[]
ok0
v[(x: 10), (x: 11), (x: 12)]
ok1
("in destroy", 10)
("in destroy", 0)
ok1
v[(x: 111), (x: 11), (x: 12)]
done
```

- [ ] bug 1: destructor for Foo(11) and Foo(12) and Foo(111) not called
- [ ] bug 2: (i can move to a separate issue) in C++ IIRC `v[0] = Foo(x:111)` shouldn't destroy `Foo(0)`, looks like there's a temporary being created and destroyed instead of a move happening

**Comment by kaushalmodi** [comment]
I do not have knowledge about destructors and "moves". Would you like to submit a PR that fixes this? Is this something that needs to be fixed here? or in Nim?

**Comment by timotheecour** [comment]
> Is this something that needs to be fixed here? or in Nim?

both here and in nim; I tried but ran into https://github.com/nim-lang/Nim/issues/14315;

**Comment by timotheecour** [comment]
this should be revived as https://github.com/nim-lang/Nim/issues/14315 was fixed

**Comment by kaushalmodi** [comment]
@timotheecour Hello!

I still don't know anything about using destructors. Can you please provide a PR?

**Comment by timotheecour** [comment]
Travelling ATM, i had a WIP PR, but need to revive it

**Comment by timotheecour** [comment]
IIRC i had revisited this but had hit another bug https://github.com/nim-lang/Nim/issues/14601 but this bug has now been fixed, so we/I should re-visit this once more!

**Comment by kaushalmodi** [comment]
@timotheecour I tried this example (copied from your original example) using the HEAD (https://github.com/Clonkk/nim-cppstl/commit/29777c7137efa9f13de01b058286d4e16c8ae104) version of `cppstl` package:

```nim
import cppstl/std_vector

type Foo = object
  x: int

proc `=destroy`*(a: var Foo) {.inline.} =
  echo ("in destroy", a.x)

proc main =
  var v1 = initCppVector[Foo]()
  echo v1
  var v = initCppVector[Foo]()
  v.add Foo(x: 10)
  v.add Foo(x: 11)
  v.add Foo(x: 12)
  echo "ok0"
  echo v
  echo "ok1"
  v[0] = Foo(x:111)
  echo "ok1"
  echo v
  echo "done"

main()
```

and now the output is:

```
[]
ok0
("in destroy", 10)
("in destroy", 11)
("in destroy", 12)
[(x: 10), (x: 11), (x: 12)]
ok1
ok1
("in destroy", 111)
("in destroy", 11)
("in destroy", 12)
[(x: 111), (x: 11), (x: 12)]
done
```

**Comment by timotheecour** [comment]
@kaushalmodi thanks for looking into this; it's still buggy, I filed https://github.com/Clonkk/nim-cppstl/issues/15
maybe we can close this since your repo was merged into the other?

**Comment by kaushalmodi** [comment]
> maybe we can close this since your repo was merged into the other?

Yep, thanks!
